server:
  port: 8080
spring:
  application:
    name: redis-study
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
logging:
  level:
    org.springframework.cache: trace
    org.springframework.data.redis: debug
